module IronmonCustomFusionPoolComponentExporter
  OUTPUT_PATH = $ironmon_custom_fusion_component_output_path.to_s
  DESCRIPTOR_PATH = $ironmon_custom_fusion_component_descriptor_path.to_s
  AUDIT_PATH = $ironmon_custom_fusion_component_audit_path.to_s
  COMPONENT_NAME = "custom_fusion_pool"

  def self.run
    pool = Ironmon.custom_fusion_pool
    bytes = Ironmon::CustomFusionComponent.encode(NB_POKEMON, pool)
    decoded = Ironmon::CustomFusionComponent.decode(bytes)
    if Ironmon::CustomFusionComponent.identities(bytes) != pool
      raise "packed custom fusion component changed deterministic pool order"
    end
    temporary_path = "#{OUTPUT_PATH}.tmp"
    File.binwrite(temporary_path, bytes)
    File.delete(OUTPUT_PATH) if File.file?(OUTPUT_PATH)
    File.rename(temporary_path, OUTPUT_PATH)

    descriptor = Ironmon::GenerationProfile.component(
      COMPONENT_NAME,
      Ironmon::CustomFusionComponent::SCHEMA_VERSION,
      OUTPUT_PATH
    )
    File.binwrite(
      DESCRIPTOR_PATH,
      Ironmon::GenerationProfile.canonical_json(descriptor) + "\n"
    )
    variants = Ironmon.custom_fusion_pool_service.validated_variants
    retained = pool.each_with_object({}) do |identity, result|
      letters = variants.fetch(identity.to_s)
      raise "eligible fusion has no validated sprite" if letters.empty?
      result[identity.to_s] = letters
    end
    sprite_path = File.join(File.dirname(OUTPUT_PATH), "generation_custom_sprites.json")
    sprite_document = {
      "schema_version" => Ironmon::ValidatedCustomSprites::SCHEMA_VERSION,
      "catalogue_id" => Ironmon::ValidatedCustomSprites.source["catalogue_id"],
      "variants" => retained
    }
    File.binwrite(sprite_path, Ironmon::GenerationProfile.canonical_json(sprite_document) + "\n")
    source_info = Ironmon.custom_fusion_pool_info
    audit = {
      "component_schema_version" =>
        Ironmon::CustomFusionComponent::SCHEMA_VERSION,
      "source_pool_schema_version" => source_info[:schema_version],
      "sprite_catalogue_id" => source_info[:sprite_catalogue_id],
      "rejected_unvalidated_sprites" => source_info[:rejected_unvalidated_sprites],
      "normal_species_count" => decoded["normal_species_count"],
      "eligible_count" => decoded["eligible_count"],
      "source_pool_fingerprint" => source_info[:fingerprint],
      "source_entry_count" => source_info[:source_entries],
      "rejected_entry_count" => source_info[:rejected_entries],
      "rejected_autogenerated_credit_count" =>
        source_info[:rejected_autogenerated_credits],
      "excluded_sprite_authors" =>
        Ironmon::CustomFusionPool::AUTOGENERATED_SPRITE_AUTHORS
    }
    File.binwrite(
      AUDIT_PATH,
      Ironmon::GenerationProfile.canonical_json(audit) + "\n"
    )
  end
end

IronmonCustomFusionPoolComponentExporter.run
