module IronmonPlayerFusionWorkerCatalogExporter
  OUTPUT_PATH = $ironmon_player_fusion_worker_catalog_output_path.to_s
  VERIFICATION_SEED = 1_187_411_801

  def self.type_codes
    types = []
    GameData::Species.each do |species|
      next if species.id_number <= 0 ||
        species.id_number >= Settings::ZAPMOLCUNO_NB
      types << species.type1 if species.type1
      types << species.type2 if species.type2
    end
    result = {}
    types.compact.uniq.map(&:to_s).sort.each_with_index do |type, index|
      result[type.to_sym] = index
    end
    return result
  end

  def self.type_mask(species, codes)
    return [species.type1, species.type2].compact.uniq.inject(0) do |mask, type|
      mask | (1 << codes.fetch(type))
    end
  end

  def self.normal_species(codes)
    (1..NB_POKEMON).map do |species_id|
      species = GameData::Species.get(species_id)
      stats = Ironmon.original_base_stats_for(species)
      [
        species_id, species.id.to_s,
        *Ironmon::BaseStatGenerator::STAT_ORDER.map { |stat| stats[stat].to_i },
        type_mask(species, codes)
      ]
    end
  end

  def self.fusion_pool(codes)
    Ironmon.custom_fusion_pool.map do |identity|
      match = /\AB(\d+)H(\d+)\z/.match(identity.to_s)
      raise "invalid custom fusion identity #{identity.inspect}" if !match
      body_id = match[1].to_i
      head_id = match[2].to_i
      species = GameData::Species.get(identity)
      [
        (body_id << Ironmon::PlayerFusionMapper::MATERIAL_ID_BITS) | head_id,
        type_mask(species, codes)
      ]
    end
  end

  def self.verification_pairs
    ids = [1, 4, 7, 25, 94, 150, 251, 384, 493, NB_POKEMON]
    result = []
    ids.each_with_index do |first, first_index|
      ids[first_index..-1].each { |second| result << [first, second] }
    end
    (1..NB_POKEMON).each do |first|
      second = ((first * 257) + 113) % NB_POKEMON + 1
      result << [first, second].sort
    end
    return result.uniq
  end

  def self.verification
    mapper = Ironmon::PlayerFusionMapper.new(
      VERIFICATION_SEED, Ironmon.custom_fusion_pool, {}, {},
      Ironmon::BaseStatGenerator.new(
        VERIFICATION_SEED, Ironmon.base_stat_source_fingerprint
      )
    )
    return verification_pairs.map do |first, second|
      results = mapper.species_pair(first, second).map do |identity|
        GameData::Species.get(identity).id_number
      end
      [first, second, results[0], results[1]]
    end
  end

  def self.run
    codes = type_codes
    info = Ironmon.custom_fusion_pool_info
    document = {
      "schema_version" => 1,
      "normal_species_count" => NB_POKEMON,
      "base_stat_source_fingerprint" =>
        Ironmon.base_stat_source_fingerprint,
      "player_fusion_generator_version" =>
        Ironmon::PlayerFusionMapper::SCHEMA_VERSION,
      "custom_fusion_pool_version" => info[:schema_version],
      "custom_fusion_pool_size" => info[:size],
      "custom_fusion_pool_fingerprint" => info[:fingerprint],
      "excluded_sprite_authors" =>
        Ironmon::CustomFusionPool::AUTOGENERATED_SPRITE_AUTHORS,
      "rejected_autogenerated_credit_count" =>
        info[:rejected_autogenerated_credits],
      "type_count" => codes.length,
      "normal_species" => normal_species(codes),
      "custom_fusion_pool" => fusion_pool(codes),
      "verification_seed" => VERIFICATION_SEED,
      "verification_mappings" => verification
    }
    temporary_path = "#{OUTPUT_PATH}.tmp"
    File.binwrite(temporary_path, JSON.generate(document) + "\n")
    File.delete(OUTPUT_PATH) if File.file?(OUTPUT_PATH)
    File.rename(temporary_path, OUTPUT_PATH)
  end
end

IronmonPlayerFusionWorkerCatalogExporter.run
