param(
    [string]$GameRoot = (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))),
    [string]$OutputPath = (Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) "data\player_fusion_worker_catalog.json"),
    [ValidateRange(60, 3600)]
    [int]$TimeoutSeconds = 900
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$resolvedGameRoot = [IO.Path]::GetFullPath($GameRoot)
$resolvedOutputPath = [IO.Path]::GetFullPath($OutputPath)
$sourceRoot = [IO.Path]::GetFullPath((Join-Path $projectRoot "src"))
$manifestPath = Join-Path $sourceRoot "load_order.json"
$loaderPath = Join-Path $PSScriptRoot "Script-Loader.rb"
$exporterPath = Join-Path $PSScriptRoot "Export-PlayerFusionWorkerCatalog.rb"
$errorPath = "$resolvedOutputPath.error"

. (Join-Path $PSScriptRoot "GameRuntime-Tooling.ps1")

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $resolvedOutputPath) | Out-Null
Remove-Item -LiteralPath $resolvedOutputPath, $errorPath, "$resolvedOutputPath.tmp" -Force -ErrorAction SilentlyContinue

$loaderSource = [IO.File]::ReadAllText($loaderPath, [Text.Encoding]::UTF8)
$rubyOutput = $resolvedOutputPath.Replace('\', '/')
$rubyGameRoot = $resolvedGameRoot.Replace('\', '/')
$rubySourceRoot = $sourceRoot.Replace('\', '/')
$rubyManifest = $manifestPath.Replace('\', '/')
$rubyExporter = ([IO.Path]::GetFullPath($exporterPath)).Replace('\', '/')
$bootstrapSource = @(
    "begin"
    "`$ironmon_player_fusion_worker_catalog_output_path = `"$rubyOutput`""
    "Dir.chdir(`"$rubyGameRoot`")"
    $loaderSource
    "IronmonScriptLoader.load_directory(`"Data/Scripts`", [/\A(?:997|998|999)/])"
    "GameData.load_all"
    "`$game_temp = Game_Temp.new"
    "Game.load_sprites_list_caches"
    "IronmonScriptLoader.load_manifest(`"$rubySourceRoot`", `"$rubyManifest`")"
    "eval(File.binread(`"$rubyExporter`"), TOPLEVEL_BINDING, `"$rubyExporter`")"
    "exit! 0"
    "rescue Exception => error"
    "backtrace = error.backtrace ? error.backtrace.join(`"\n`") : `"`""
    "File.binwrite(`"$($errorPath.Replace('\', '/'))`", `"#{error.class}: #{error.message}\n#{backtrace}`")"
    "exit! 1"
    "end"
) -join "`n"

try {
    Invoke-IronmonGameRuntime `
        -GameRoot $resolvedGameRoot `
        -RubySource $bootstrapSource `
        -TimeoutSeconds $TimeoutSeconds `
        -OperationName "player-fusion worker catalog generation" `
        -ErrorReportPath $errorPath

    if (-not (Test-Path -LiteralPath $resolvedOutputPath)) {
        throw "The bundled runtime did not produce the player-fusion worker catalog."
    }
    $document = Get-Content -LiteralPath $resolvedOutputPath -Raw | ConvertFrom-Json
    if ($document.custom_fusion_pool_size -ne $document.custom_fusion_pool.Count -or
        $document.normal_species_count -ne $document.normal_species.Count) {
        throw "The player-fusion worker catalog counts are inconsistent."
    }
    if (@($document.excluded_sprite_authors) -notcontains "japeal") {
        throw "The player-fusion worker catalog does not record the autogenerated-sprite exclusion."
    }
    Write-Output "Player-fusion worker catalog generated: $($document.normal_species_count) materials, $($document.custom_fusion_pool_size) custom results."
}
finally {
    Remove-Item -LiteralPath $errorPath, "$resolvedOutputPath.tmp" -Force -ErrorAction SilentlyContinue
}
