#===============================================================================
# Release-stable complete-fusion predecessor candidates
#===============================================================================

module Ironmon
  FUSION_PREDECESSOR_INDEX_PATH = File.join(
    "Data", "Ironmon", "fusion_predecessor_index.dat"
  )
  FUSION_PREDECESSOR_INDEX_CACHE_DIRECTORY = File.join(
    "Data", "Ironmon", "fusion_predecessor_indexes"
  )

  class FusionPredecessorIndexError < StandardError
  end

  class FusionPredecessorIndex
    SCHEMA_VERSION = 1

    def initialize(document, catalog, fusion_pool, fusion_pool_info)
      @document = document
      validate(catalog, fusion_pool, fusion_pool_info)
      @source_ids_by_signature = {}
    end

    def source_ids_for(bucket, types)
      result = []
      seen = {}
      types.each do |type|
        source_ids_for_signature(bucket, type).each do |source_id|
          next if seen[source_id]
          seen[source_id] = true
          result << source_id
        end
      end
      result.sort!
      return result.freeze
    end

    def membership_count
      return @document["membership_count"]
    end

    def packed_pool_membership
      return @document["packed_pool_membership"]
    end

    private

    def source_ids_for_signature(bucket, type)
      key = "#{bucket}|#{type}"
      cached = @source_ids_by_signature[key]
      return cached if cached
      packed = @document["signatures"][key]
      source_ids = packed ? packed.unpack("L<*") : []
      @source_ids_by_signature[key] = source_ids.freeze
      return @source_ids_by_signature[key]
    end

    def validate(catalog, fusion_pool, fusion_pool_info)
      if !@document.is_a?(Hash) ||
         @document["schema_version"] != SCHEMA_VERSION ||
         !@document["signatures"].is_a?(Hash)
        raise FusionPredecessorIndexError,
              "unsupported fusion predecessor index schema"
      end
      expected = {
        "normal_species_count" => NB_POKEMON,
        "source_fingerprint" => catalog.source_fingerprint,
        "taxonomy_fingerprint" => catalog.taxonomy_fingerprint,
        "method_fingerprint" => catalog.method_fingerprint,
        "fusion_pool_schema_version" => fusion_pool_info[:schema_version],
        "fusion_pool_size" => fusion_pool_info[:size],
        "fusion_pool_fingerprint" => fusion_pool_info[:fingerprint],
        "excluded_sprite_authors" =>
          CustomFusionPool::AUTOGENERATED_SPRITE_AUTHORS
      }
      expected.each do |key, value|
        next if @document[key] == value
        raise FusionPredecessorIndexError,
              "fusion predecessor index #{key} does not match runtime data"
      end
      rejected_autogenerated_credits =
        @document["rejected_autogenerated_credit_count"]
      if !rejected_autogenerated_credits.is_a?(Integer) ||
         rejected_autogenerated_credits < 0
        raise FusionPredecessorIndexError,
              "fusion predecessor index autogenerated-credit audit is invalid"
      end
      valid_source_ids = {}
      packed_pool_membership = "\0" *
        (((NB_POKEMON * NB_POKEMON) + 7) / 8)
      fusion_pool.each do |species_id|
        match = /\AB(\d+)H(\d+)\z/.match(species_id.to_s)
        if !match
          raise FusionPredecessorIndexError,
                "fusion predecessor index received an invalid fusion pool"
        end
        source_id = (match[1].to_i * NB_POKEMON) + match[2].to_i
        valid_source_ids[source_id] = true
        position = ((match[1].to_i - 1) * NB_POKEMON) +
          match[2].to_i - 1
        byte_index = position >> 3
        packed_pool_membership.setbyte(
          byte_index,
          packed_pool_membership.getbyte(byte_index) | (1 << (position & 7))
        )
      end
      if @document["packed_pool_membership"] != packed_pool_membership
        raise FusionPredecessorIndexError,
              "fusion predecessor index pool membership does not match"
      end
      membership_count = @document["signatures"].values.inject(0) do |sum, packed|
        if !packed.is_a?(String) || packed.bytesize % 4 != 0
          raise FusionPredecessorIndexError,
                "fusion predecessor index contains malformed source data"
        end
        previous_source_id = 0
        packed.unpack("L<*").each do |source_id|
          if source_id <= previous_source_id || !valid_source_ids[source_id]
            raise FusionPredecessorIndexError,
                  "fusion predecessor index contains a non-pool source"
          end
          previous_source_id = source_id
        end
        sum + (packed.bytesize / 4)
      end
      if membership_count != @document["membership_count"]
        raise FusionPredecessorIndexError,
              "fusion predecessor index membership count does not match"
      end
    end
  end

  def self.fusion_predecessor_index
    return @fusion_predecessor_index if @fusion_predecessor_index
    catalog = evolution_catalog
    fusion_pool = custom_fusion_pool
    fusion_pool_info = custom_fusion_pool_info
    cached_path = runtime_fusion_predecessor_index_path(fusion_pool_info)
    errors = []
    [cached_path, FUSION_PREDECESSOR_INDEX_PATH].each do |path|
      next if !File.file?(path)
      begin
        document = File.open(path, "rb") do |file|
          Marshal.load(file)
        end
        @fusion_predecessor_index = FusionPredecessorIndex.new(
          document, catalog, fusion_pool, fusion_pool_info
        )
        return @fusion_predecessor_index
      rescue Exception => exception
        errors << "#{File.basename(path)}: #{exception.message}"
      end
    end
    reason = errors.empty? ? "no compatible index is installed" :
      errors.join("; ")
    echoln "Ironmon is rebuilding its fusion predecessor index for the " +
      "installed custom-sprite pool: #{reason}"
    document = build_runtime_fusion_predecessor_index_document(
      catalog, fusion_pool, fusion_pool_info
    )
    @fusion_predecessor_index = FusionPredecessorIndex.new(
      document, catalog, fusion_pool, fusion_pool_info
    )
    persist_runtime_fusion_predecessor_index(cached_path, document)
    return @fusion_predecessor_index
  rescue Exception => exception
    raise FusionPredecessorIndexError,
          "The fusion predecessor index is unavailable: #{exception.message}"
  end

  def self.runtime_fusion_predecessor_index_path(fusion_pool_info)
    fingerprint = fusion_pool_info[:fingerprint].to_s
    if fingerprint !~ /\A[0-9a-f]{16}\z/
      raise FusionPredecessorIndexError,
            "the custom fusion pool fingerprint is invalid"
    end
    return File.join(
      FUSION_PREDECESSOR_INDEX_CACHE_DIRECTORY,
      "#{fingerprint}.dat"
    )
  end

  def self.persist_runtime_fusion_predecessor_index(path, document)
    directory = File.dirname(path)
    Dir.mkdir(directory) if !Dir.exist?(directory)
    temporary_path = "#{path}.#{Process.pid}.tmp"
    File.open(temporary_path, "wb") do |file|
      Marshal.dump(document, file)
      file.flush
    end
    File.delete(path) if File.exist?(path)
    File.rename(temporary_path, path)
    return true
  rescue Exception => exception
    echoln "Ironmon could not cache its rebuilt fusion predecessor index: " +
      exception.message
    return false
  ensure
    File.delete(temporary_path) if temporary_path &&
      File.exist?(temporary_path)
  end

  def self.build_runtime_fusion_predecessor_index_document(
    catalog, fusion_pool, fusion_pool_info
  )
    taxonomy = {}
    catalog.taxonomy_catalog.each do |entry|
      taxonomy[entry[:identity]] = entry
    end
    component_signatures = Hash.new { |hash, key| hash[key] = {} }
    catalog.branch_catalog.each do |branch|
      component = GameData::Species.get(branch[:source])
      base_component = GameData::Species.get(component.id_number)
      next if base_component.id.to_s != branch[:source]
      role = taxonomy.fetch(branch[:source])[:role]
      buckets = if role == :intermediate
                  [:terminal]
                elsif role == :first_stage
                  [:continuing, :terminal]
                else
                  []
                end
      required_types = catalog.required_target_types(component, branch)
      buckets.each do |bucket|
        required_types.each do |type|
          component_signatures[component.id_number][
            "#{bucket}|#{type}"
          ] = true
        end
      end
    end
    signatures = Hash.new { |hash, key| hash[key] = {} }
    packed_pool_membership = "\0" *
      (((NB_POKEMON * NB_POKEMON) + 7) / 8)
    fusion_pool.each do |species_id|
      match = /\AB(\d+)H(\d+)\z/.match(species_id.to_s)
      if !match
        raise FusionPredecessorIndexError,
              "the custom fusion pool contains an invalid identity"
      end
      body_id = match[1].to_i
      head_id = match[2].to_i
      source_id = (body_id * NB_POKEMON) + head_id
      position = ((body_id - 1) * NB_POKEMON) + head_id - 1
      byte_index = position >> 3
      packed_pool_membership.setbyte(
        byte_index,
        packed_pool_membership.getbyte(byte_index) | (1 << (position & 7))
      )
      [body_id, head_id].uniq.each do |component_id|
        component_signatures[component_id].each_key do |signature|
          signatures[signature][source_id] = true
        end
      end
    end
    packed_signatures = {}
    membership_count = 0
    signatures.keys.sort.each do |signature|
      source_ids = signatures[signature].keys.sort
      membership_count += source_ids.length
      packed_signatures[signature] = source_ids.pack("L<*")
    end
    return {
      "schema_version" => FusionPredecessorIndex::SCHEMA_VERSION,
      "normal_species_count" => NB_POKEMON,
      "source_fingerprint" => catalog.source_fingerprint,
      "taxonomy_fingerprint" => catalog.taxonomy_fingerprint,
      "method_fingerprint" => catalog.method_fingerprint,
      "fusion_pool_schema_version" => fusion_pool_info[:schema_version],
      "fusion_pool_size" => fusion_pool_info[:size],
      "fusion_pool_fingerprint" => fusion_pool_info[:fingerprint],
      "excluded_sprite_authors" =>
        CustomFusionPool::AUTOGENERATED_SPRITE_AUTHORS,
      "rejected_autogenerated_credit_count" =>
        fusion_pool_info[:rejected_autogenerated_credits],
      "membership_count" => membership_count,
      "packed_pool_membership" => packed_pool_membership,
      "signatures" => packed_signatures
    }
  end

  def self.reset_fusion_predecessor_index_cache
    @fusion_predecessor_index = nil
  end
end
