<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <Using Include="Xunit" />
    <ProjectReference Include="../../tools/Ironmon.ReleaseTool/Ironmon.ReleaseTool.csproj" />
    <ProjectReference Include="../../tools/Ironmon.SpriteSizeTool/Ironmon.SpriteSizeTool.csproj" />
    <ProjectReference Include="../../src/Ironmon.Setup.Core/Ironmon.Setup.Core.csproj" />
    <ProjectReference Include="../../src/Ironmon.Updater.Core/Ironmon.Updater.Core.csproj" />
    <ProjectReference Include="../../src/Ironmon.Updater.Infrastructure/Ironmon.Updater.Infrastructure.csproj" />
    <ProjectReference Include="../Ironmon.Updater.CrashHost/Ironmon.Updater.CrashHost.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
