module IronmonValidatedSpriteRuntimeTests
  def self.assert(condition, message)
    raise "Validated sprite test failed: #{message}" if !condition
  end

  def self.with_method(target, name, replacement)
    original = target.method(name)
    target.define_singleton_method(name, &replacement)
    yield
  ensure
    target.define_singleton_method(name, original)
  end

  def self.run
    test_source_pool_filter
    profile = Ironmon.current_generation_profile
    variants = Ironmon::ValidatedCustomSprites.profile_variants
    pool = Ironmon::CustomFusionComponent.identities(File.binread(
      Ironmon.generation_profile_component_path("custom_fusion_pool")
    ))
    assert(variants.keys.sort == pool.map(&:to_s).sort,
      "every admitted fusion has pinned usable variants, including after odd-tail removal")
    assert(variants.values.all? { |letters| !letters.empty? },
      "no admitted fusion depends on an autogenerated fallback")

    legacy = Marshal.load(Marshal.dump(profile["manifest"]))
    legacy["algorithms"].find { |entry| entry["name"] == "custom_fusion_eligibility" }["version"] = 1
    legacy["components"].reject! { |entry| entry["name"] == "custom_sprites" }
    assert(Ironmon.validate_generation_profile_components(legacy, profile["root"], "legacy fixture"),
      "historical four-component profiles do not require a new sprite component")
    legacy["algorithms"].find { |entry| entry["name"] == "custom_fusion_eligibility" }["version"] = 2
    begin
      Ironmon.validate_generation_profile_components(legacy, profile["root"], "incomplete fixture")
      raise "missing version-2 sprite component was accepted"
    rescue Ironmon::GenerationProfileUnavailable
    end
    with_method(Ironmon, :generation_profile_algorithm_version, proc { |*_| 1 }) do
      assert(Ironmon::ValidatedCustomSprites.profile_variants.nil?,
        "an old run retains its original sprite choices")
    end

    expected = { "a" => "main", "b" => "temp" }
    with_method(Ironmon::ValidatedCustomSprites, :allowed_statuses, proc { |*_| expected }) do
      sprite = PIFSprite.new(:AUTOGEN, 561, 505, "")
      sprite.local_path = "old-unvalidated.png"
      result = Ironmon.validated_pif_sprite(sprite)
      assert(result.equal?(sprite) && result.type == :CUSTOM &&
        result.alt_letter == "a" && result.local_path.nil?,
        "a stored unvalidated choice becomes a permitted custom variant")
      result.alt_letter = "b"
      assert(Ironmon.validated_pif_sprite(result).alt_letter == "b",
        "an already permitted choice remains unchanged")
      assert(map_alt_sprite_letters_for_pokemon("561.505") == expected,
        "game selection receives only pinned variants and retains main/temp status")
      normal = PIFSprite.new(:BASE, 1, nil, "c")
      assert(Ironmon.validated_pif_sprite(normal).alt_letter == "c",
        "normal species keep their existing sprite policy")
    end
    with_method(Ironmon::ValidatedCustomSprites, :allowed_statuses, proc { |*_| nil }) do
      sprite = PIFSprite.new(:CUSTOM, 561, 505, "old")
      assert(Ironmon.validated_pif_sprite(sprite).alt_letter == "old",
        "legacy sprite choices are not rewritten by the new catalogue")
    end
  end

  def self.test_source_pool_filter
    visible = { "1.1a" => true, "1.2" => true, "2.1" => true, "2.2" => true }
    credits = ["1.1,artist,main", "1.1a,artist,temp", "1.2,japeal,main",
      "2.1,artist,main", "2.2,artist,main"]
    indexed = ["1.1.png", "1.1a.png", "1.2.png", "2.1.png"]
    original_foreach = File.method(:foreach)
    replacement = proc do |path, &block|
      if path == Settings::CREDITS_FILE_PATH
        credits.each(&block)
      elsif path == Settings::CUSTOM_SPRITES_FILE_PATH
        indexed.each(&block)
      else
        original_foreach.call(path, &block)
      end
    end
    with_method(File, :foreach, replacement) do
      with_method(Ironmon::ValidatedCustomSprites, :visible_index, proc { visible }) do
        index = { :B1H1 => [], :B2H1 => [], :B1H2 => [], :B2H2 => [] }
        service = Ironmon::CustomFusionPool.new(index)
        assert(service.pool == [:B1H1, :B1H2],
          "visible temporary variants qualify; blank, Japeal and removed index variants do not")
        assert(service.validated_variants["B1H1"] == { "a" => "temp" },
          "a transparent main cannot enter the renderer choices through a valid alternate")
        indexed << "2.2.png"
        assert(Ironmon::CustomFusionPool.new(index).pool == [:B1H1, :B1H2],
          "validation retains deterministic removal of the odd tail")
      end
    end
  end
end

IronmonValidatedSpriteRuntimeTests.run
