<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/Ironmon.SpriteLibrary/Ironmon.SpriteLibrary.csproj" /></ItemGroup>
  <ItemGroup><InternalsVisibleTo Include="Ironmon.Updater.Tests" /></ItemGroup>
</Project>
