using Ironmon.Tracker.Connection.Obtainability;
using System.Diagnostics;
using System.Text;

namespace Ironmon.Tracker.Tests.Connection;

/// <summary>
/// Verifies the parallel tracker-side player-fusion mapping prototype against Ruby-generated reference data.
/// </summary>
public sealed class PlayerFusionMappingWorkerTests
{
    private const string DefaultFormSuffix = ":0";
    private const string ColdStartJobId = "cold-start-worker-job";
    private const string ColdStartRunId = "cold-start-worker-run";
    private const string DirectProofJobId = "direct-proof-job";
    private const string FusionBodyPrefix = "B";
    private const string FusionHeadSeparator = "H";
    private const string MismatchedSourceCatalogFingerprint = "0000000000000000";
    private const string RuntimePoolEncounterJobId = "runtime-index-pool-encounters";
    private const string RuntimePoolJobId = "runtime-index-pool-worker";
    private const string WorkerRunId = "worker-run";
    private const string WildMappingKind = "wild";

    /// <summary>
    /// Verifies the continuous range's breakpoint and both upside and downside caps.
    /// </summary>
    [Theory]
    [InlineData(700, 700, 700, 750)]
    [InlineData(600, 560, 600, 635)]
    [InlineData(600, 559, 600, 635)]
    [InlineData(600, 550, 592, 633)]
    [InlineData(600, 500, 563, 625)]
    [InlineData(600, 200, 520, 610)]
    [InlineData(600, 100, 520, 608)]
    [InlineData(300, 100, 260, 310)]
    public void FusionBstRangeMatchesContinuousRule(int firstBst, int secondBst, int expectedMinimum, int expectedMaximum)
    {
        (int minimum, int maximum) = PlayerFusionMappingWorker.FusionBstRange(firstBst, secondBst);

        Assert.Equal(expectedMinimum, minimum);
        Assert.Equal(expectedMaximum, maximum);
    }

    /// <summary>
    /// Verifies global reverse pairs remain close in strength across representative seeds.
    /// </summary>
    [Theory]
    [InlineData(1_187_411_801)]
    [InlineData(1_792_136_788)]
    [InlineData(1_689)]
    [InlineData(2_895)]
    [InlineData(116_872_428)]
    [InlineData(1_851_036_422)]
    public void GlobalReversePairsRemainStrengthCompatible(long seed)
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingWorker worker = new(catalog);

        PlayerFusionPairingAudit audit = worker.AuditPairing(seed, catalog.PlayerFusionGeneratorVersion);

        Assert.Equal(catalog.CustomFusionPool.Count / 2, audit.PairCount);
        Assert.True(audit.MaximumLegalRangeWidth > 0);
        Assert.True(audit.MaximumBstDifference <= audit.MaximumLegalRangeWidth, $"Seed {seed} has a global reverse pair differing by {audit.MaximumBstDifference} BST, while the widest legal material interval is {audit.MaximumLegalRangeWidth} BST.");
        Assert.True(audit.PairsWithoutSharedType <= audit.PairCount / 100, $"Seed {seed} has {audit.PairsWithoutSharedType} global reverse pairs without a shared type.");
    }

    /// <summary>
    /// Verifies the tracker can consume the same generated semantic source catalog as the game.
    /// </summary>
    [Fact]
    public void ObtainabilitySourceCatalogContainsParsedSourcesAndResources()
    {
        ObtainabilitySourceCatalog catalog = ObtainabilitySourceCatalog.Load();

        Assert.Equal(1, catalog.SchemaVersion);
        Assert.Equal(16, catalog.Fingerprint.Length);
        Assert.NotEmpty(catalog.Sources);
        Assert.NotEmpty(catalog.Resources);
        Assert.Contains(catalog.Sources, source => source.MappingKind == WildMappingKind && source.MappingContext.Count > 0);
        Assert.Contains(catalog.Resources, resource => resource.Repeatable);
        Assert.Contains(catalog.Resources, resource => resource.TmGift);
    }

    /// <summary>
    /// Verifies every generated cross-runtime mapping and the explicit autogenerated-sprite exclusion.
    /// </summary>
    [Fact]
    public void MapAllMatchesRubyReferenceMappings()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingWorker worker = new(catalog);
        int[] materials = [.. catalog.VerificationMappings.SelectMany(mapping => new[] { mapping.FirstMaterialId, mapping.SecondMaterialId }).Distinct()];

        Dictionary<(int First, int Second), PlayerFusionMappedPair> actual = worker.MapAll(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion, materials)
            .ToDictionary(mapping => (mapping.FirstMaterialId, mapping.SecondMaterialId));

        Assert.Contains("japeal", catalog.ExcludedSpriteAuthors, StringComparer.OrdinalIgnoreCase);
        foreach (PlayerFusionReferenceMapping expected in catalog.VerificationMappings)
        {
            PlayerFusionMappedPair mapping = actual[(expected.FirstMaterialId, expected.SecondMaterialId)];
            Assert.Equal(expected.FirstResultId, mapping.FirstResultId);
            Assert.Equal(expected.SecondResultId, mapping.SecondResultId);
            Assert.Equal(expected.FirstResultId, worker.MapOrderedPair(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion, expected.FirstMaterialId, expected.SecondMaterialId));
            if (expected.FirstMaterialId != expected.SecondMaterialId)
                Assert.Equal(expected.SecondResultId, worker.MapOrderedPair(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion, expected.SecondMaterialId, expected.FirstMaterialId));
        }
    }

    /// <summary>
    /// Rejects the isolated 824-BST fusion in save H's seed without exhaustively retrying impossible repairs.
    /// </summary>
    [Fact]
    public void IsolatedFusionReportsAnImpossiblePairingPromptly()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingWorker worker = new(catalog);
        Stopwatch elapsed = Stopwatch.StartNew();

        InvalidOperationException error = Assert.Throws<InvalidOperationException>(() => worker.AuditPairing(1_271_448_503, catalog.PlayerFusionGeneratorVersion));

        Assert.Contains("271035 (824 BST)", error.Message, StringComparison.Ordinal);
        Assert.Contains("within 92 BST", error.Message, StringComparison.Ordinal);
        Assert.True(elapsed.Elapsed < TimeSpan.FromSeconds(10), $"An impossible pairing took {elapsed.Elapsed} to reject.");
    }

    /// <summary>
    /// Verifies a migrated sprite pool can replace the embedded pool while all
    /// mapping work remains in the parallel tracker worker.
    /// </summary>
    [Fact]
    public async Task RuntimeIndexMembershipBuildsPoolSpecificParallelWorkers()
    {
        PlayerFusionMappingWorkerCatalog embedded = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionTargetSpecies[] retained = [.. embedded.CustomFusionPool.Take(embedded.CustomFusionPool.Count - 2)];
        byte[] membership = new byte[(embedded.NormalSpeciesCount * embedded.NormalSpeciesCount + 7) / 8];
        foreach (PlayerFusionTargetSpecies target in retained)
        {
            int bodyId = target.PackedComponents >> 10;
            int headId = target.PackedComponents & 0x3FF;
            int position = (bodyId - 1) * embedded.NormalSpeciesCount + headId - 1;
            membership[position >> 3] |= (byte)(1 << (position & 7));
        }

        string fingerprint = FusionPoolFingerprint(retained);
        PlayerFusionMappingWorkerCatalog runtime = embedded.WithRuntimeFusionPool(embedded.CustomFusionPoolVersion, retained.Length, fingerprint, Convert.ToBase64String(membership));
        PlayerFusionMappingWorker mappingWorker = new(runtime);
        FusionEvolutionAssignmentWorker evolutionWorker = new(runtime);

        Assert.Equal(retained.Length, runtime.CustomFusionPool.Count);
        Assert.Equal(fingerprint, runtime.CustomFusionPoolFingerprint);
        Assert.Equal(6, mappingWorker.MapAll(runtime.VerificationSeed, runtime.PlayerFusionGeneratorVersion, [1, 4, 7]).Count);
        FusionEvolutionSourceAssignment assignment = evolutionWorker.Generate(runtime.VerificationSeed, runtime.CustomFusionPool[0].PackedComponents);
        Assert.NotNull(assignment);
        Assert.Equal(retained.Length + 2, embedded.CustomFusionPool.Count);

        int[] materials = [.. Enumerable.Range(1, runtime.NormalSpeciesCount)];
        PlayerFusionClosureWorkPayload work = new()
        {
            JobId = RuntimePoolJobId,
            SourceCatalogFingerprint = ObtainabilitySourceCatalog.Load().Fingerprint,
            Seed = runtime.VerificationSeed,
            GeneratorVersion = runtime.PlayerFusionGeneratorVersion,
            BaseStatSourceFingerprint = runtime.BaseStatSourceFingerprint,
            CustomFusionPoolVersion = runtime.CustomFusionPoolVersion,
            CustomFusionPoolSize = runtime.CustomFusionPool.Count,
            CustomFusionPoolFingerprint = runtime.CustomFusionPoolFingerprint,
            PackedCustomFusionPool = Convert.ToBase64String(membership),
            FusionEvolutionGeneratorVersion = runtime.FusionEvolutionGeneratorVersion,
            FusionEvolutionRulesVersion = runtime.FusionEvolutionRulesVersion,
            EvolutionSourceFingerprint = runtime.EvolutionSourceFingerprint,
            EvolutionTaxonomyFingerprint = runtime.EvolutionTaxonomyFingerprint,
            EvolutionMethodFingerprint = runtime.EvolutionMethodFingerprint,
            MaterialIds = materials,
            BaseProofs = [.. materials.Select(id => new PlayerFusionProofSpeciesPayload
            {
                SpeciesId = id,
                Plans = [.. Enumerable.Range(1, 4).Select(pathLength =>
                    new PlayerFusionProofPlanPayload { PathLength = pathLength })]
            })],
            TotalPairs = materials.Length * (materials.Length + 1) / 2
        };

        PlayerFusionMappingCoordinator coordinator = new();
        FusionAssignmentRecipePayload assignmentRecipe = new()
        {
            Seed = work.Seed,
            PlayerFusionGeneratorVersion = work.GeneratorVersion,
            GeneratorVersion = work.FusionEvolutionGeneratorVersion,
            RulesVersion = work.FusionEvolutionRulesVersion,
            SourceFingerprint = work.EvolutionSourceFingerprint,
            TaxonomyFingerprint = work.EvolutionTaxonomyFingerprint,
            MethodFingerprint = work.EvolutionMethodFingerprint,
            BaseStatSourceFingerprint = work.BaseStatSourceFingerprint,
            TargetPoolVersion = work.CustomFusionPoolVersion,
            TargetPoolSize = work.CustomFusionPoolSize,
            TargetPoolFingerprint = work.CustomFusionPoolFingerprint,
            PackedCustomFusionPool = work.PackedCustomFusionPool
        };

        Assert.True(coordinator.PrepareActiveFusionAssignments(WorkerRunId, assignmentRecipe));
        PlayerFusionClosureWorkPayload directWork = new()
        {
            JobId = RuntimePoolEncounterJobId,
            SourceCatalogFingerprint = work.SourceCatalogFingerprint,
            Seed = work.Seed,
            GeneratorVersion = work.GeneratorVersion,
            BaseStatSourceFingerprint = work.BaseStatSourceFingerprint,
            CustomFusionPoolVersion = work.CustomFusionPoolVersion,
            CustomFusionPoolSize = work.CustomFusionPoolSize,
            CustomFusionPoolFingerprint = work.CustomFusionPoolFingerprint,
            PackedCustomFusionPool = work.PackedCustomFusionPool,
            FusionEvolutionGeneratorVersion = work.FusionEvolutionGeneratorVersion,
            FusionEvolutionRulesVersion = work.FusionEvolutionRulesVersion,
            EvolutionSourceFingerprint = work.EvolutionSourceFingerprint,
            EvolutionTaxonomyFingerprint = work.EvolutionTaxonomyFingerprint,
            EvolutionMethodFingerprint = work.EvolutionMethodFingerprint,
            MaterialIds = work.MaterialIds,
            TotalPairs = work.TotalPairs,
            DirectPairOffsets = [1],
            DirectEncounterOnly = true
        };
        PlayerFusionClosureResultPayload directResult = await coordinator.CreateResultAsync(directWork, CancellationToken.None)
            ?? throw new InvalidOperationException("The migrated runtime-pool encounter result was not created.");

        int[] expectedDirect =
        [
            mappingWorker.MapOrderedPair(runtime.VerificationSeed, runtime.PlayerFusionGeneratorVersion, 1, 2),
            mappingWorker.MapOrderedPair(runtime.VerificationSeed, runtime.PlayerFusionGeneratorVersion, 2, 1)
        ];
        Array.Sort(expectedDirect);
        Assert.Equal(expectedDirect, directResult.DirectEncounterFusionIds);
        Assert.Empty(directResult.ObtainableFusionWords);

        PlayerFusionClosureResultPayload result = await coordinator.CreateResultAsync(work, CancellationToken.None)
            ?? throw new InvalidOperationException("The migrated runtime-pool worker result was not created.");

        Assert.NotEmpty(result.ObtainableFusionWords);
        Assert.True(result.ObtainableCount > materials.Length);
        Assert.Equal(0, coordinator.CachedJobCount);
    }

    /// <summary>
    /// Calculates the runtime-compatible fingerprint for an ordered custom-fusion pool.
    /// </summary>
    /// <param name="pool">The ordered custom-fusion targets to fingerprint.</param>
    /// <returns>The lowercase hexadecimal FNV-1a pool fingerprint.</returns>
    private static string FusionPoolFingerprint(IReadOnlyList<PlayerFusionTargetSpecies> pool)
    {
        const ulong offsetBasis = 14_695_981_039_346_656_037;
        const ulong prime = 1_099_511_628_211;
        ulong value = offsetBasis;
        foreach (PlayerFusionTargetSpecies target in pool)
        {
            int bodyId = target.PackedComponents >> 10;
            int headId = target.PackedComponents & 0x3FF;
            foreach (byte entry in Encoding.UTF8.GetBytes($"B{bodyId}H{headId}"))
            {
                value ^= entry;
                value = unchecked(value * prime);
            }

            value = unchecked(value * prime);
        }

        return value.ToString("x16");
    }

    /// <summary>
    /// Guards the representative full material workload against falling back to game-runtime-scale latency.
    /// </summary>
    [Fact]
    public void MapAllCompletesRepresentativeWorkloadWithinPrototypeBudget()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingWorker worker = new(catalog);
        int[] materials = [.. Enumerable.Range(1, catalog.NormalSpeciesCount)];
        Stopwatch stopwatch = Stopwatch.StartNew();

        IReadOnlyList<PlayerFusionMappedPair> mappings = worker.MapAll(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion, materials);

        stopwatch.Stop();
        Assert.Equal(catalog.NormalSpeciesCount * (catalog.NormalSpeciesCount + 1) / 2, mappings.Count);
        Assert.True(stopwatch.Elapsed < TimeSpan.FromSeconds(15), $"Parallel player-fusion mapping took {stopwatch.Elapsed.TotalSeconds:F3} seconds.");

        Dictionary<int, int> reversePartners = [];
        foreach (PlayerFusionMappedPair mapping in mappings)
        {
            Assert.NotEqual(mapping.FirstResultId, mapping.SecondResultId);
            AssertPartner(reversePartners, mapping.FirstResultId, mapping.SecondResultId);
            AssertPartner(reversePartners, mapping.SecondResultId, mapping.FirstResultId);
        }

        PlayerFusionPairingAudit audit = worker.AuditPairing(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion);
        Assert.Equal(catalog.CustomFusionPool.Count / 2, audit.PairCount);
        Assert.True(audit.MaximumBstDifference <= audit.MaximumLegalRangeWidth, $"The widest global reverse pair differs by {audit.MaximumBstDifference} BST, while the widest legal material interval is {audit.MaximumLegalRangeWidth} BST.");
        Assert.True(audit.PairsWithoutSharedType <= audit.PairCount / 100, $"{audit.PairsWithoutSharedType} global reverse pairs do not share a type.");
    }

    /// <summary>
    /// Verifies one result always has the same global reverse partner.
    /// </summary>
    private static void AssertPartner(Dictionary<int, int> partners, int resultId, int expectedPartnerId)
    {
        if (partners.TryGetValue(resultId, out int actualPartnerId))
        {
            Assert.Equal(expectedPartnerId, actualPartnerId);
        }
        else
        {
            partners.Add(resultId, expectedPartnerId);
        }
    }

    /// <summary>
    /// Verifies every mapped result exposes the same seed-specific global reverse partner as Ruby.
    /// </summary>
    [Fact]
    public void ReversePartnerMatchesRubyReferenceMapping()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingWorker worker = new(catalog);
        PlayerFusionReferenceMapping reference = catalog.VerificationMappings[0];

        Assert.Equal(reference.SecondResultId, worker.ReversePartner(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion, reference.FirstResultId));
        Assert.Equal(reference.FirstResultId, worker.ReversePartner(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion, reference.SecondResultId));
    }

    /// <summary>
    /// Verifies direct wild pairs and caught-fusion reversals remain provable when ordinary material fusion is excluded.
    /// </summary>
    [Fact]
    public async Task CoordinatorIncludesDirectAndReversedFusionProofs()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionReferenceMapping directReference = catalog.VerificationMappings.First(mapping => mapping.FirstMaterialId != mapping.SecondMaterialId);
        PlayerFusionReferenceMapping caughtReference = catalog.VerificationMappings.First(mapping => mapping.FirstResultId != directReference.FirstResultId && mapping.FirstResultId != directReference.SecondResultId);
        int[] materials = [.. new[] { directReference.FirstMaterialId, directReference.SecondMaterialId }.Order()];
        PlayerFusionClosureWorkPayload directWork = new()
        {
            JobId = $"{DirectProofJobId}:encounters",
            SourceCatalogFingerprint = ObtainabilitySourceCatalog.Load().Fingerprint,
            Seed = catalog.VerificationSeed,
            GeneratorVersion = catalog.PlayerFusionGeneratorVersion,
            BaseStatSourceFingerprint = catalog.BaseStatSourceFingerprint,
            CustomFusionPoolVersion = catalog.CustomFusionPoolVersion,
            CustomFusionPoolSize = catalog.CustomFusionPool.Count,
            CustomFusionPoolFingerprint = catalog.CustomFusionPoolFingerprint,
            FusionEvolutionGeneratorVersion = catalog.FusionEvolutionGeneratorVersion,
            FusionEvolutionRulesVersion = catalog.FusionEvolutionRulesVersion,
            EvolutionSourceFingerprint = catalog.EvolutionSourceFingerprint,
            EvolutionTaxonomyFingerprint = catalog.EvolutionTaxonomyFingerprint,
            EvolutionMethodFingerprint = catalog.EvolutionMethodFingerprint,
            MaterialIds = materials,
            TotalPairs = 3,
            DirectPairOffsets = [1],
            DirectEncounterOnly = true
        };

        PlayerFusionClosureWorkPayload work = new()
        {
            JobId = DirectProofJobId,
            SourceCatalogFingerprint = ObtainabilitySourceCatalog.Load().Fingerprint,
            Seed = catalog.VerificationSeed,
            GeneratorVersion = catalog.PlayerFusionGeneratorVersion,
            BaseStatSourceFingerprint = catalog.BaseStatSourceFingerprint,
            CustomFusionPoolVersion = catalog.CustomFusionPoolVersion,
            CustomFusionPoolSize = catalog.CustomFusionPool.Count,
            CustomFusionPoolFingerprint = catalog.CustomFusionPoolFingerprint,
            FusionEvolutionGeneratorVersion = catalog.FusionEvolutionGeneratorVersion,
            FusionEvolutionRulesVersion = catalog.FusionEvolutionRulesVersion,
            EvolutionSourceFingerprint = catalog.EvolutionSourceFingerprint,
            EvolutionTaxonomyFingerprint = catalog.EvolutionTaxonomyFingerprint,
            EvolutionMethodFingerprint = catalog.EvolutionMethodFingerprint,
            MaterialIds = materials,
            TotalPairs = 3,
            ExcludedPairOffsets = [0, 1, 2],
            DirectPairOffsets = [1],
            ReversibleFusionIds = [caughtReference.FirstResultId],
            BaseProofs =
            [
                .. materials.Select(id => new PlayerFusionProofSpeciesPayload
                {
                    SpeciesId = id,
                    Plans = [new PlayerFusionProofPlanPayload { PathLength = 1 }]
                }),
                new PlayerFusionProofSpeciesPayload
                {
                    SpeciesId = caughtReference.FirstResultId,
                    Plans = [new PlayerFusionProofPlanPayload { PathLength = 1 }]
                }
            ]
        };
        PlayerFusionMappingCoordinator coordinator = new();

        PlayerFusionClosureResultPayload directResult = await coordinator.CreateResultAsync(directWork, CancellationToken.None)
            ?? throw new InvalidOperationException("The compatible derived-encounter worker result was not created.");

        int[] expectedDirectEncounterFusions = [directReference.FirstResultId, directReference.SecondResultId];
        Array.Sort(expectedDirectEncounterFusions);
        Assert.Equal(expectedDirectEncounterFusions, directResult.DirectEncounterFusionIds);
        Assert.Empty(directResult.ObtainableFusionWords);
        Assert.Empty(directResult.PackedExecutableEvolutionEdges);
        Assert.Equal(0, directResult.ObtainableCount);

        PlayerFusionClosureResultPayload result = await coordinator.CreateResultAsync(work, CancellationToken.None)
            ?? throw new InvalidOperationException("The compatible direct-proof worker result was not created.");

        Assert.True(IsObtainable(result, directReference.FirstResultId));
        Assert.True(IsObtainable(result, directReference.SecondResultId));
        Assert.True(IsObtainable(result, caughtReference.SecondResultId));
        Assert.Equal(expectedDirectEncounterFusions, result.DirectEncounterFusionIds);
    }

    /// <summary>
    /// Reads one numeric fusion membership bit from a compact worker result.
    /// </summary>
    /// <param name="result">The compact closure result.</param>
    /// <param name="speciesId">The numeric fusion identifier.</param>
    /// <returns>True when the result marks the fusion obtainable.</returns>
    private static bool IsObtainable(PlayerFusionClosureResultPayload result, int speciesId)
        => (result.ObtainableFusionWords[speciesId >> 5] & 1U << (speciesId & 31)) != 0;

    /// <summary>
    /// Verifies a cold full-material closure cannot deadlock with the concurrently prepared evolution index.
    /// </summary>
    [Fact]
    public async Task CoordinatorColdStartCompletesConcurrentWorkerPreparation()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingCoordinator coordinator = new();
        int[] materials = [.. Enumerable.Range(1, catalog.NormalSpeciesCount)];
        PlayerFusionClosureWorkPayload work = new()
        {
            JobId = ColdStartJobId,
            SourceCatalogFingerprint = ObtainabilitySourceCatalog.Load().Fingerprint,
            Seed = 1_851_036_422,
            GeneratorVersion = catalog.PlayerFusionGeneratorVersion,
            BaseStatSourceFingerprint = catalog.BaseStatSourceFingerprint,
            CustomFusionPoolVersion = catalog.CustomFusionPoolVersion,
            CustomFusionPoolSize = catalog.CustomFusionPool.Count,
            CustomFusionPoolFingerprint = catalog.CustomFusionPoolFingerprint,
            FusionEvolutionGeneratorVersion = catalog.FusionEvolutionGeneratorVersion,
            FusionEvolutionRulesVersion = catalog.FusionEvolutionRulesVersion,
            EvolutionSourceFingerprint = catalog.EvolutionSourceFingerprint,
            EvolutionTaxonomyFingerprint = catalog.EvolutionTaxonomyFingerprint,
            EvolutionMethodFingerprint = catalog.EvolutionMethodFingerprint,
            MaterialIds = materials,
            BaseProofs = [.. materials.Select(id => new PlayerFusionProofSpeciesPayload
            {
                SpeciesId = id,
                Plans = [new PlayerFusionProofPlanPayload { PathLength = 1 }]
            })],
            TotalPairs = materials.Length * (materials.Length + 1) / 2
        };

        FusionAssignmentRecipePayload assignmentRecipe = new()
        {
            Seed = work.Seed,
            PlayerFusionGeneratorVersion = catalog.PlayerFusionGeneratorVersion,
            GeneratorVersion = catalog.FusionEvolutionGeneratorVersion,
            RulesVersion = catalog.FusionEvolutionRulesVersion,
            SourceFingerprint = catalog.EvolutionSourceFingerprint,
            TaxonomyFingerprint = catalog.EvolutionTaxonomyFingerprint,
            MethodFingerprint = catalog.EvolutionMethodFingerprint,
            BaseStatSourceFingerprint = catalog.BaseStatSourceFingerprint,
            TargetPoolVersion = catalog.CustomFusionPoolVersion,
            TargetPoolSize = catalog.CustomFusionPool.Count,
            TargetPoolFingerprint = catalog.CustomFusionPoolFingerprint
        };

        Assert.True(coordinator.PrepareActiveFusionAssignments(ColdStartRunId, assignmentRecipe));
        PlayerFusionClosureResultPayload? result = await coordinator.CreateResultAsync(work, CancellationToken.None, ColdStartRunId).WaitAsync(TimeSpan.FromSeconds(20));

        Assert.NotNull(result);
        Assert.NotEmpty(result.ObtainableFusionWords);
        Assert.Equal(0, coordinator.CachedJobCount);

        Stopwatch pageClock = Stopwatch.StartNew();
        IReadOnlyList<AreaFusionResultPayload>? page = await coordinator.MapAreaFusionsAsync(ColdStartRunId, null,
            [new FusionMaterialAssignmentPayload { BodyId = 25, HeadId = 4 }, new FusionMaterialAssignmentPayload { BodyId = 4, HeadId = 25 }], CancellationToken.None);
        Assert.NotNull(page);
        Assert.Equal(2, page.Count);
        Assert.All(page, entry => Assert.True(IsObtainable(result, entry.SpeciesNumber)));
        Assert.NotEqual(page[0].SpeciesNumber, page[1].SpeciesNumber);
        Assert.True(pageClock.Elapsed < TimeSpan.FromSeconds(1));
        Assert.Null(await coordinator.MapAreaFusionsAsync(WorkerRunId, null, [], CancellationToken.None));
    }

    /// <summary>
    /// Verifies the tracker returns one compact final closure summary.
    /// </summary>
    [Fact]
    public async Task CoordinatorCreatesCompactClosureSummary()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingCoordinator coordinator = new();
        int[] materials = [.. Enumerable.Range(1, 519)];
        PlayerFusionClosureWorkPayload work = new()
        {
            JobId = "worker-batch-test",
            SourceCatalogFingerprint = ObtainabilitySourceCatalog.Load().Fingerprint,
            Seed = catalog.VerificationSeed,
            GeneratorVersion = catalog.PlayerFusionGeneratorVersion,
            BaseStatSourceFingerprint = catalog.BaseStatSourceFingerprint,
            CustomFusionPoolVersion = catalog.CustomFusionPoolVersion,
            CustomFusionPoolSize = catalog.CustomFusionPool.Count,
            CustomFusionPoolFingerprint = catalog.CustomFusionPoolFingerprint,
            FusionEvolutionGeneratorVersion = catalog.FusionEvolutionGeneratorVersion,
            FusionEvolutionRulesVersion = catalog.FusionEvolutionRulesVersion,
            EvolutionSourceFingerprint = catalog.EvolutionSourceFingerprint,
            EvolutionTaxonomyFingerprint = catalog.EvolutionTaxonomyFingerprint,
            EvolutionMethodFingerprint = catalog.EvolutionMethodFingerprint,
            MaterialIds = materials,
            BaseProofs = [.. materials.Select(id => new PlayerFusionProofSpeciesPayload
            {
                SpeciesId = id,
                Plans = [new PlayerFusionProofPlanPayload { PathLength = 1 }]
            })],
            ResourceSupply = catalog.EvolutionBranches
                .SelectMany(branch => branch.ItemOptions)
                .Where(item => !string.IsNullOrEmpty(item))
                .Distinct(StringComparer.Ordinal)
                .ToDictionary(item => item, _ => 2_000, StringComparer.Ordinal),
            TotalPairs = 134_940
        };

        FusionAssignmentRecipePayload assignmentRecipe = new()
        {
            Seed = catalog.VerificationSeed,
            PlayerFusionGeneratorVersion = catalog.PlayerFusionGeneratorVersion,
            GeneratorVersion = catalog.FusionEvolutionGeneratorVersion,
            RulesVersion = catalog.FusionEvolutionRulesVersion,
            SourceFingerprint = catalog.EvolutionSourceFingerprint,
            TaxonomyFingerprint = catalog.EvolutionTaxonomyFingerprint,
            MethodFingerprint = catalog.EvolutionMethodFingerprint,
            BaseStatSourceFingerprint = catalog.BaseStatSourceFingerprint,
            TargetPoolVersion = catalog.CustomFusionPoolVersion,
            TargetPoolSize = catalog.CustomFusionPool.Count,
            TargetPoolFingerprint = catalog.CustomFusionPoolFingerprint
        };
        Assert.True(coordinator.PrepareActiveFusionAssignments(WorkerRunId, assignmentRecipe));

        PlayerFusionReferenceMapping materialReference = catalog.VerificationMappings[0];
        int materialTargetBodyId = (materialReference.FirstResultId - 1) / catalog.NormalSpeciesCount;
        int materialTargetHeadId = materialReference.FirstResultId - materialTargetBodyId * catalog.NormalSpeciesCount;
        PlayerFusionMaterialPage? materialPage = await coordinator.GetActiveFusionMaterialAssignmentsAsync(WorkerRunId, $"{FusionBodyPrefix}{materialTargetBodyId}{FusionHeadSeparator}{materialTargetHeadId}{DefaultFormSuffix}", 0, int.MaxValue, CancellationToken.None);
        Assert.NotNull(materialPage);
        Assert.Contains(materialPage.Assignments, assignment => assignment.BodyId == materialReference.FirstMaterialId && assignment.HeadId == materialReference.SecondMaterialId);

        byte[]? membership = await coordinator.GetOccurrenceFusionMaterialsAsync(WorkerRunId, null, $"{FusionBodyPrefix}{materialTargetBodyId}{FusionHeadSeparator}{materialTargetHeadId}{DefaultFormSuffix}", CancellationToken.None);
        Assert.NotNull(membership);
        Assert.Equal((catalog.NormalSpeciesCount * catalog.NormalSpeciesCount + 7) / 8, membership.Length);
        int bitCount = membership.Sum(value => System.Numerics.BitOperations.PopCount((uint)value));
        Assert.Equal(materialPage.Total, bitCount);
        foreach (FusionMaterialAssignmentPayload assignment in materialPage.Assignments)
        {
            int position = (assignment.BodyId - 1) * catalog.NormalSpeciesCount + assignment.HeadId - 1;
            Assert.NotEqual(0, membership[position / 8] & (1 << (position % 8)));
        }

        Assert.Null(await coordinator.GetOccurrenceFusionMaterialsAsync(null, null, $"{FusionBodyPrefix}{materialTargetBodyId}{FusionHeadSeparator}{materialTargetHeadId}{DefaultFormSuffix}", CancellationToken.None));

        PlayerFusionEvolutionReferenceMapping reference = catalog.EvolutionVerificationMappings.First(mapping => mapping.Seed == catalog.VerificationSeed && mapping.Branches.Count > 0);
        int targetId = reference.Branches[0].TargetId;
        int targetBodyId = (targetId - 1) / catalog.NormalSpeciesCount;
        int targetHeadId = targetId - targetBodyId * catalog.NormalSpeciesCount;
        int sourceBodyId = reference.PackedSourceComponents >> 10;
        int sourceHeadId = reference.PackedSourceComponents & 0x3FF;
        int expectedSourceId = sourceBodyId * catalog.NormalSpeciesCount + sourceHeadId;
        IReadOnlyList<EvolutionPredecessorAssignmentPayload>? earlyPredecessorAssignments = await coordinator.GetActiveEvolutionPredecessorAssignmentsAsync(WorkerRunId, $"{FusionBodyPrefix}{targetBodyId}{FusionHeadSeparator}{targetHeadId}{DefaultFormSuffix}", CancellationToken.None);
        Assert.NotNull(earlyPredecessorAssignments);
        Assert.Contains(earlyPredecessorAssignments, assignment => assignment.SourceId == expectedSourceId && assignment.ComponentBranchIdentity == reference.Branches[0].ComponentBranchIdentity);

        PlayerFusionClosureResultPayload foreground = await coordinator.CreateResultAsync(work, CancellationToken.None, WorkerRunId)
            ?? throw new InvalidOperationException("The compatible foreground worker result was not created.");

        Assert.NotEmpty(foreground.ObtainableFusionWords);
        Assert.NotEmpty(foreground.PackedExecutableEvolutionEdges);
        Assert.True(foreground.PackedExecutableEvolutionEdges.Length < TrackerProtocol.MaximumMessageCharacters / 2);
        Assert.True(foreground.ObtainableCount > materials.Length);
        string serialized = TrackerJson.SerializePayload(new DebugPokemonObtainabilityRequestPayload { Foreground = true, FusionClosureResult = foreground }).GetRawText();
        Assert.True(serialized.Length < TrackerProtocol.MaximumMessageCharacters, $"The complete native closure summary required {serialized.Length} characters.");
        Assert.Equal(0, coordinator.CachedJobCount);

        IReadOnlyList<EvolutionPredecessorAssignmentPayload>? predecessorAssignments = await coordinator.GetActiveEvolutionPredecessorAssignmentsAsync(WorkerRunId, $"{FusionBodyPrefix}{targetBodyId}{FusionHeadSeparator}{targetHeadId}{DefaultFormSuffix}", CancellationToken.None);
        Assert.NotNull(predecessorAssignments);
        Assert.Contains(predecessorAssignments, assignment => assignment.SourceId == expectedSourceId && assignment.ComponentBranchIdentity == reference.Branches[0].ComponentBranchIdentity);

        string incompatibleJson = TrackerJson.SerializePayload(work).GetRawText().Replace(work.SourceCatalogFingerprint, MismatchedSourceCatalogFingerprint, StringComparison.Ordinal);
        using JsonDocument incompatibleDocument = JsonDocument.Parse(incompatibleJson);
        PlayerFusionClosureWorkPayload incompatible = TrackerJson.DeserializePayload<PlayerFusionClosureWorkPayload>(incompatibleDocument.RootElement);
        InvalidOperationException error = await Assert.ThrowsAsync<InvalidOperationException>(() => coordinator.CreateResultAsync(incompatible, CancellationToken.None));
        Assert.Contains("source catalogs do not match", error.Message, StringComparison.Ordinal);
    }
}
