using Ironmon.Tracker.Connection.Obtainability;
using System.Diagnostics;

namespace Ironmon.Tracker.Tests.Connection;

/// <summary>
/// Verifies the parallel tracker-side player-fusion mapping prototype against Ruby-generated reference data.
/// </summary>
public sealed class PlayerFusionMappingWorkerTests
{
    private const string DefaultFormSuffix = ":0";
    private const string FusionBodyPrefix = "B";
    private const string FusionHeadSeparator = "H";
    private const string MismatchedSourceCatalogFingerprint = "0000000000000000";
    private const string WorkerRunId = "worker-run";
    private const string WildMappingKind = "wild";

    /// <summary>
    /// Verifies the tracker can consume the same generated semantic source catalog as the game.
    /// </summary>
    [Fact]
    public void ObtainabilitySourceCatalogContainsParsedSourcesAndResources()
    {
        ObtainabilitySourceCatalog catalog = ObtainabilitySourceCatalog.Load();

        Assert.Equal(1, catalog.SchemaVersion);
        Assert.Equal(16, catalog.Fingerprint.Length);
        Assert.NotEmpty(catalog.Sources);
        Assert.NotEmpty(catalog.Resources);
        Assert.Contains(catalog.Sources, source => source.MappingKind == WildMappingKind && source.MappingContext.Count > 0);
        Assert.Contains(catalog.Resources, resource => resource.Repeatable);
        Assert.Contains(catalog.Resources, resource => resource.TmGift);
    }

    /// <summary>
    /// Verifies every generated cross-runtime mapping and the explicit autogenerated-sprite exclusion.
    /// </summary>
    [Fact]
    public void MapAllMatchesRubyReferenceMappings()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingWorker worker = new(catalog);
        int[] materials = [.. catalog.VerificationMappings.SelectMany(mapping => new[] { mapping.FirstMaterialId, mapping.SecondMaterialId }).Distinct()];

        Dictionary<(int First, int Second), PlayerFusionMappedPair> actual = worker.MapAll(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion, materials)
            .ToDictionary(mapping => (mapping.FirstMaterialId, mapping.SecondMaterialId));

        Assert.Contains("japeal", catalog.ExcludedSpriteAuthors, StringComparer.OrdinalIgnoreCase);
        foreach (PlayerFusionReferenceMapping expected in catalog.VerificationMappings)
        {
            PlayerFusionMappedPair mapping = actual[(expected.FirstMaterialId, expected.SecondMaterialId)];
            Assert.Equal(expected.FirstResultId, mapping.FirstResultId);
            Assert.Equal(expected.SecondResultId, mapping.SecondResultId);
        }
    }

    /// <summary>
    /// Guards the representative full material workload against falling back to game-runtime-scale latency.
    /// </summary>
    [Fact]
    public void MapAllCompletesRepresentativeWorkloadWithinPrototypeBudget()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingWorker worker = new(catalog);
        int[] materials = [.. Enumerable.Range(1, 519)];
        Stopwatch stopwatch = Stopwatch.StartNew();

        IReadOnlyList<PlayerFusionMappedPair> mappings = worker.MapAll(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion, materials);

        stopwatch.Stop();
        Assert.Equal(134_940, mappings.Count);
        Assert.True(stopwatch.Elapsed < TimeSpan.FromSeconds(15), $"Parallel player-fusion mapping took {stopwatch.Elapsed.TotalSeconds:F3} seconds.");
    }

    /// <summary>
    /// Verifies the tracker returns one compact final closure summary.
    /// </summary>
    [Fact]
    public async Task CoordinatorCreatesCompactClosureSummary()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingCoordinator coordinator = new();
        int[] materials = [.. Enumerable.Range(1, 519)];
        PlayerFusionClosureWorkPayload work = new()
        {
            JobId = "worker-batch-test",
            SourceCatalogFingerprint = ObtainabilitySourceCatalog.Load().Fingerprint,
            Seed = catalog.VerificationSeed,
            GeneratorVersion = catalog.PlayerFusionGeneratorVersion,
            BaseStatSourceFingerprint = catalog.BaseStatSourceFingerprint,
            CustomFusionPoolVersion = catalog.CustomFusionPoolVersion,
            CustomFusionPoolSize = catalog.CustomFusionPool.Count,
            CustomFusionPoolFingerprint = catalog.CustomFusionPoolFingerprint,
            FusionEvolutionGeneratorVersion = catalog.FusionEvolutionGeneratorVersion,
            FusionEvolutionRulesVersion = catalog.FusionEvolutionRulesVersion,
            EvolutionSourceFingerprint = catalog.EvolutionSourceFingerprint,
            EvolutionTaxonomyFingerprint = catalog.EvolutionTaxonomyFingerprint,
            EvolutionMethodFingerprint = catalog.EvolutionMethodFingerprint,
            MaterialIds = materials,
            BaseProofs = [.. materials.Select(id => new PlayerFusionProofSpeciesPayload
            {
                SpeciesId = id,
                Plans = [new PlayerFusionProofPlanPayload { PathLength = 1 }]
            })],
            ResourceSupply = catalog.EvolutionBranches
                .SelectMany(branch => branch.ItemOptions)
                .Where(item => !string.IsNullOrEmpty(item))
                .Distinct(StringComparer.Ordinal)
                .ToDictionary(item => item, _ => 2_000, StringComparer.Ordinal),
            TotalPairs = 134_940
        };

        FusionAssignmentRecipePayload assignmentRecipe = new()
        {
            Seed = catalog.VerificationSeed,
            PlayerFusionGeneratorVersion = catalog.PlayerFusionGeneratorVersion,
            GeneratorVersion = catalog.FusionEvolutionGeneratorVersion,
            RulesVersion = catalog.FusionEvolutionRulesVersion,
            SourceFingerprint = catalog.EvolutionSourceFingerprint,
            TaxonomyFingerprint = catalog.EvolutionTaxonomyFingerprint,
            MethodFingerprint = catalog.EvolutionMethodFingerprint,
            BaseStatSourceFingerprint = catalog.BaseStatSourceFingerprint,
            TargetPoolVersion = catalog.CustomFusionPoolVersion,
            TargetPoolSize = catalog.CustomFusionPool.Count,
            TargetPoolFingerprint = catalog.CustomFusionPoolFingerprint
        };
        Assert.True(coordinator.PrepareActiveFusionAssignments(WorkerRunId, assignmentRecipe));

        PlayerFusionReferenceMapping materialReference = catalog.VerificationMappings[0];
        int materialTargetBodyId = (materialReference.FirstResultId - 1) / catalog.NormalSpeciesCount;
        int materialTargetHeadId = materialReference.FirstResultId - materialTargetBodyId * catalog.NormalSpeciesCount;
        PlayerFusionMaterialPage? materialPage = await coordinator.GetActiveFusionMaterialAssignmentsAsync(WorkerRunId, $"{FusionBodyPrefix}{materialTargetBodyId}{FusionHeadSeparator}{materialTargetHeadId}{DefaultFormSuffix}", 0, int.MaxValue, CancellationToken.None);
        Assert.NotNull(materialPage);
        Assert.Contains(materialPage.Assignments, assignment => assignment.BodyId == materialReference.FirstMaterialId && assignment.HeadId == materialReference.SecondMaterialId);

        PlayerFusionEvolutionReferenceMapping reference = catalog.EvolutionVerificationMappings.First(mapping => mapping.Seed == catalog.VerificationSeed && mapping.Branches.Count > 0);
        int targetId = reference.Branches[0].TargetId;
        int targetBodyId = (targetId - 1) / catalog.NormalSpeciesCount;
        int targetHeadId = targetId - targetBodyId * catalog.NormalSpeciesCount;
        int sourceBodyId = reference.PackedSourceComponents >> 10;
        int sourceHeadId = reference.PackedSourceComponents & 0x3FF;
        int expectedSourceId = sourceBodyId * catalog.NormalSpeciesCount + sourceHeadId;
        IReadOnlyList<EvolutionPredecessorAssignmentPayload>? earlyPredecessorAssignments = await coordinator.GetActiveEvolutionPredecessorAssignmentsAsync(WorkerRunId, $"{FusionBodyPrefix}{targetBodyId}{FusionHeadSeparator}{targetHeadId}{DefaultFormSuffix}", CancellationToken.None);
        Assert.NotNull(earlyPredecessorAssignments);
        Assert.Contains(earlyPredecessorAssignments, assignment => assignment.SourceId == expectedSourceId && assignment.ComponentBranchIdentity == reference.Branches[0].ComponentBranchIdentity);

        PlayerFusionClosureResultPayload foreground = await coordinator.CreateResultAsync(work, CancellationToken.None, WorkerRunId)
            ?? throw new InvalidOperationException("The compatible foreground worker result was not created.");

        Assert.NotEmpty(foreground.ObtainableFusionWords);
        Assert.NotEmpty(foreground.PackedExecutableEvolutionEdges);
        Assert.True(foreground.PackedExecutableEvolutionEdges.Length < TrackerProtocol.MaximumMessageCharacters / 2);
        Assert.True(foreground.ObtainableCount > materials.Length);
        string serialized = TrackerJson.SerializePayload(new DebugPokemonObtainabilityRequestPayload { Foreground = true, FusionClosureResult = foreground }).GetRawText();
        Assert.True(serialized.Length < TrackerProtocol.MaximumMessageCharacters, $"The complete native closure summary required {serialized.Length} characters.");
        Assert.Equal(0, coordinator.CachedJobCount);

        IReadOnlyList<EvolutionPredecessorAssignmentPayload>? predecessorAssignments = await coordinator.GetActiveEvolutionPredecessorAssignmentsAsync(WorkerRunId, $"{FusionBodyPrefix}{targetBodyId}{FusionHeadSeparator}{targetHeadId}{DefaultFormSuffix}", CancellationToken.None);
        Assert.NotNull(predecessorAssignments);
        Assert.Contains(predecessorAssignments, assignment => assignment.SourceId == expectedSourceId && assignment.ComponentBranchIdentity == reference.Branches[0].ComponentBranchIdentity);

        string incompatibleJson = TrackerJson.SerializePayload(work).GetRawText().Replace(work.SourceCatalogFingerprint, MismatchedSourceCatalogFingerprint, StringComparison.Ordinal);
        using JsonDocument incompatibleDocument = JsonDocument.Parse(incompatibleJson);
        PlayerFusionClosureWorkPayload incompatible = TrackerJson.DeserializePayload<PlayerFusionClosureWorkPayload>(incompatibleDocument.RootElement);
        InvalidOperationException error = await Assert.ThrowsAsync<InvalidOperationException>(() => coordinator.CreateResultAsync(incompatible, CancellationToken.None));
        Assert.Contains("source catalogs do not match", error.Message, StringComparison.Ordinal);
    }
}
