using Ironmon.Tracker.Connection.Obtainability;
using System.Diagnostics;

namespace Ironmon.Tracker.Tests.Connection;

/// <summary>
/// Verifies the parallel tracker-side player-fusion mapping prototype against Ruby-generated reference data.
/// </summary>
public sealed class PlayerFusionMappingWorkerTests
{
    /// <summary>
    /// Verifies every generated cross-runtime mapping and the explicit autogenerated-sprite exclusion.
    /// </summary>
    [Fact]
    public void MapAllMatchesRubyReferenceMappings()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingWorker worker = new(catalog);
        int[] materials = [.. catalog.VerificationMappings.SelectMany(mapping => new[] { mapping.FirstMaterialId, mapping.SecondMaterialId }).Distinct()];

        Dictionary<(int First, int Second), PlayerFusionMappedPair> actual = worker.MapAll(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion, materials)
            .ToDictionary(mapping => (mapping.FirstMaterialId, mapping.SecondMaterialId));

        Assert.Contains("japeal", catalog.ExcludedSpriteAuthors, StringComparer.OrdinalIgnoreCase);
        foreach (PlayerFusionReferenceMapping expected in catalog.VerificationMappings)
        {
            PlayerFusionMappedPair mapping = actual[(expected.FirstMaterialId, expected.SecondMaterialId)];
            Assert.Equal(expected.FirstResultId, mapping.FirstResultId);
            Assert.Equal(expected.SecondResultId, mapping.SecondResultId);
        }
    }

    /// <summary>
    /// Guards the representative full material workload against falling back to game-runtime-scale latency.
    /// </summary>
    [Fact]
    public void MapAllCompletesRepresentativeWorkloadWithinPrototypeBudget()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingWorker worker = new(catalog);
        int[] materials = [.. Enumerable.Range(1, 332)];
        Stopwatch stopwatch = Stopwatch.StartNew();

        IReadOnlyList<PlayerFusionMappedPair> mappings = worker.MapAll(catalog.VerificationSeed, catalog.PlayerFusionGeneratorVersion, materials);

        stopwatch.Stop();
        Assert.Equal(55_278, mappings.Count);
        Assert.True(stopwatch.Elapsed < TimeSpan.FromSeconds(15), $"Parallel player-fusion mapping took {stopwatch.Elapsed.TotalSeconds:F3} seconds.");
    }

    /// <summary>
    /// Verifies foreground and background result batches remain bounded and resume at the game-owned offset.
    /// </summary>
    [Fact]
    public async Task CoordinatorCreatesBoundedOrderedBatches()
    {
        PlayerFusionMappingWorkerCatalog catalog = PlayerFusionMappingWorkerCatalog.Load();
        PlayerFusionMappingCoordinator coordinator = new();
        int[] materials = [.. Enumerable.Range(1, 332)];
        PlayerFusionMappingWorkPayload work = new()
        {
            JobId = "worker-batch-test",
            Seed = catalog.VerificationSeed,
            GeneratorVersion = catalog.PlayerFusionGeneratorVersion,
            BaseStatSourceFingerprint = catalog.BaseStatSourceFingerprint,
            CustomFusionPoolVersion = catalog.CustomFusionPoolVersion,
            CustomFusionPoolSize = catalog.CustomFusionPool.Count,
            CustomFusionPoolFingerprint = catalog.CustomFusionPoolFingerprint,
            MaterialIds = materials,
            ProcessedPairs = 0,
            TotalPairs = 55_278
        };

        PlayerFusionMappingBatchPayload foreground = await coordinator.CreateBatchAsync(work, true, CancellationToken.None)
            ?? throw new InvalidOperationException("The compatible foreground worker batch was not created.");

        PlayerFusionMappingWorkPayload resumed = new()
        {
            JobId = work.JobId,
            Seed = work.Seed,
            GeneratorVersion = work.GeneratorVersion,
            BaseStatSourceFingerprint = work.BaseStatSourceFingerprint,
            CustomFusionPoolVersion = work.CustomFusionPoolVersion,
            CustomFusionPoolSize = work.CustomFusionPoolSize,
            CustomFusionPoolFingerprint = work.CustomFusionPoolFingerprint,
            MaterialIds = work.MaterialIds,
            ProcessedPairs = foreground.PackedPairs.Count / 4,
            TotalPairs = work.TotalPairs
        };

        PlayerFusionMappingBatchPayload background = await coordinator.CreateBatchAsync(resumed, false, CancellationToken.None)
            ?? throw new InvalidOperationException("The compatible background worker batch was not created.");

        Assert.Equal(8_192 * 4, foreground.PackedPairs.Count);
        Assert.Equal(0, foreground.Offset);
        Assert.Equal(128 * 4, background.PackedPairs.Count);
        Assert.Equal(8_192, background.Offset);
        Assert.True(background.PackedPairs[0] > 0);
        Assert.True(background.PackedPairs[1] >= background.PackedPairs[0]);
        Assert.Equal(1, coordinator.CachedJobCount);

        PlayerFusionMappingWorkPayload finalWork = new()
        {
            JobId = resumed.JobId,
            Seed = resumed.Seed,
            GeneratorVersion = resumed.GeneratorVersion,
            BaseStatSourceFingerprint = resumed.BaseStatSourceFingerprint,
            CustomFusionPoolVersion = resumed.CustomFusionPoolVersion,
            CustomFusionPoolSize = resumed.CustomFusionPoolSize,
            CustomFusionPoolFingerprint = resumed.CustomFusionPoolFingerprint,
            MaterialIds = resumed.MaterialIds,
            ProcessedPairs = resumed.TotalPairs - 1,
            TotalPairs = resumed.TotalPairs
        };
        PlayerFusionMappingBatchPayload final = await coordinator.CreateBatchAsync(finalWork, true, CancellationToken.None)
            ?? throw new InvalidOperationException("The compatible final worker batch was not created.");

        Assert.Equal(4, final.PackedPairs.Count);
        Assert.Equal(finalWork.TotalPairs - 1, final.Offset);
        Assert.Equal(0, coordinator.CachedJobCount);
    }
}
