namespace Ironmon.Tracker.Seeds;

/// <summary>
/// Defines the fixed application contract for locally shareable seeded-run tokens.
/// </summary>
public static class SeedTokenConstants
{
    /// <summary>
    /// Gets the JWS protected-header type.
    /// </summary>
    public const string TokenType = "ironmon-seed+jwt";

    /// <summary>
    /// Gets the token issuer.
    /// </summary>
    public const string Issuer = "ironmon-tracker";

    /// <summary>
    /// Gets the token audience.
    /// </summary>
    public const string Audience = "ironmon-game";

    /// <summary>
    /// Gets the dedicated local seed-token key identifier.
    /// </summary>
    public const string KeyId = "ironmon-seed-local-v1";

    /// <summary>
    /// Gets the token contract version.
    /// </summary>
    public const int ContractVersion = 1;

    /// <summary>
    /// Gets the supported game configuration schema version.
    /// </summary>
    public const int ConfigurationSchemaVersion = 1;

    /// <summary>
    /// Gets the token contract-version claim.
    /// </summary>
    public const string VersionClaim = "ver";

    /// <summary>
    /// Gets the run-seed claim.
    /// </summary>
    public const string SeedClaim = "seed";

    /// <summary>
    /// Gets the game-version claim.
    /// </summary>
    public const string GameVersionClaim = "game_version";

    /// <summary>
    /// Gets the Ironmon-version claim.
    /// </summary>
    public const string IronmonVersionClaim = "ironmon_version";

    /// <summary>
    /// Gets the game-data-mode claim.
    /// </summary>
    public const string DataModeClaim = "data_mode";

    /// <summary>
    /// Gets the configuration claim.
    /// </summary>
    public const string ConfigurationClaim = "configuration";

    /// <summary>
    /// Gets the compatibility-fingerprint claim.
    /// </summary>
    public const string CompatibilityFingerprintClaim = "compatibility_fingerprint";

    /// <summary>
    /// Gets the nested configuration schema-version property.
    /// </summary>
    public const string ConfigurationVersionProperty = "schema_version";

    /// <summary>
    /// Gets the nested wild-policy property.
    /// </summary>
    public const string WildPolicyProperty = "wild_policy";

    /// <summary>
    /// Gets the nested trainer-policy property.
    /// </summary>
    public const string TrainerPolicyProperty = "trainer_policy";

    /// <summary>
    /// Gets the nested unfusion-setting property.
    /// </summary>
    public const string UnfusionSettingProperty = "unfusion_setting";

    /// <summary>
    /// Gets the nested automatic-reset property.
    /// </summary>
    public const string AutomaticResetProperty = "automatic_reset";

    /// <summary>
    /// Gets the inclusive minimum run seed.
    /// </summary>
    public const long MinimumSeed = 0;

    /// <summary>
    /// Gets the inclusive maximum run seed generated by the game.
    /// </summary>
    public const long MaximumSeed = 2_147_483_646;

    /// <summary>
    /// Gets the minimum accepted HMAC key size in bytes.
    /// </summary>
    public const int MinimumKeySize = 32;

    /// <summary>
    /// Gets the maximum compact-token length.
    /// </summary>
    public const int MaximumTokenLength = 32_768;

    /// <summary>
    /// Gets the maximum token-ID length.
    /// </summary>
    public const int MaximumTokenIdLength = 128;

    /// <summary>
    /// Gets the maximum version or data-mode identifier length.
    /// </summary>
    public const int MaximumIdentifierLength = 128;

    /// <summary>
    /// Gets the seeded-run token file extension.
    /// </summary>
    public const string FileExtension = ".ironmon-seed";
}
