<#
.SYNOPSIS
Checks exact generation dependencies, complete cache contents and corruption rejection.
#>
$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $true
. (Join-Path $PSScriptRoot 'GenerationCache.ps1')
$root = Join-Path ([IO.Path]::GetTempPath()) ('ironmon-generation-cache-' + [guid]::NewGuid().ToString('N'))
$source = Join-Path $root 'source'
$cache = Join-Path $root 'cache'
$restored = Join-Path $root 'restored'
$assertions = 0
function Assert-CacheCondition([bool]$Condition, [string]$Message) {
  if (-not $Condition) { throw $Message }
  $script:assertions++
}
function Assert-CacheRejected([scriptblock]$Operation) {
  $rejected = $false
  try { & $Operation | Out-Null } catch { $rejected = $true }
  Assert-CacheCondition $rejected 'Invalid generated cache was accepted.'
}
try {
  New-Item -ItemType Directory -Path "$source/src/foundation", "$source/tools/generation", "$source/tracker", $restored -Force | Out-Null
  git -C $source init --quiet
  '  VERSION = "1.0.0"' | Set-Content "$source/src/foundation/Core.rb"
  'generator v1' | Set-Content "$source/tools/generation/export.rb"
  $recipe = "# BEGIN GENERATED CATALOG RECIPE`ngenerate v1`n# END GENERATED CATALOG RECIPE"
  $recipe | Set-Content "$source/tools/Build-TrackerRelease.ps1"
  'tracker v1' | Set-Content "$source/tracker/app.cs"
  $fingerprint = 'a' * 64
  $key = Get-GenerationCacheKey $source $fingerprint
  Assert-CacheCondition ($key -ceq (Get-GenerationCacheKey $source $fingerprint)) 'Identical generation inputs changed the cache key.'
  'tracker v2' | Set-Content "$source/tracker/app.cs"
  Assert-CacheCondition ($key -ceq (Get-GenerationCacheKey $source $fingerprint)) 'A tracker-only change invalidated generated catalogs.'
  Add-Content "$source/tools/Build-TrackerRelease.ps1" 'test orchestration changed'
  Assert-CacheCondition ($key -ceq (Get-GenerationCacheKey $source $fingerprint)) 'Test orchestration invalidated generated catalogs.'
  $recipe.Replace('generate v1', 'generate v2') | Set-Content "$source/tools/Build-TrackerRelease.ps1"
  Assert-CacheCondition ($key -cne (Get-GenerationCacheKey $source $fingerprint)) 'Changed generation arguments reused old catalogs.'
  'unbounded generation' | Set-Content "$source/tools/Build-TrackerRelease.ps1"
  Assert-CacheRejected { Get-GenerationCacheKey $source $fingerprint }
  $recipe | Set-Content "$source/tools/Build-TrackerRelease.ps1"
  '  VERSION = "1.0.1"' | Set-Content "$source/src/foundation/Core.rb"
  Assert-CacheCondition ($key -ceq (Get-GenerationCacheKey $source $fingerprint)) 'A displayed release-version change invalidated gameplay components.'
  Assert-CacheCondition ($key -cne (Get-GenerationCacheKey $source ('b' * 64))) 'Changed upstream game or metadata reused old catalogs.'
  Add-Content "$source/src/foundation/Core.rb" '  RULE = 2'
  Assert-CacheCondition ($key -cne (Get-GenerationCacheKey $source $fingerprint)) 'Changed gameplay source reused old catalogs.'
  '  VERSION = "1.0.1"' | Set-Content "$source/src/foundation/Core.rb"
  'generator v2' | Set-Content "$source/tools/generation/export.rb"
  Assert-CacheCondition ($key -cne (Get-GenerationCacheKey $source $fingerprint)) 'Changed generator code reused old catalogs.'
  'generator v1' | Set-Content "$source/tools/generation/export.rb"
  foreach ($relative in Get-GenerationCacheFiles) {
    $path = Join-Path $source $relative
    New-Item -ItemType Directory -Path (Split-Path -Parent $path) -Force | Out-Null
    [IO.File]::WriteAllText($path, "generated fixture: $relative")
  }
  Assert-CacheCondition (-not (Restore-GenerationCache $restored $cache $key)) 'A missing cache was treated as reusable.'
  Save-GenerationCache $source $cache $key
  Assert-CacheCondition (Restore-GenerationCache $restored $cache $key) 'A complete verified cache could not be restored.'
  foreach ($relative in Get-GenerationCacheFiles) {
    Assert-CacheCondition ((Get-FileHash (Join-Path $source $relative)).Hash -ceq (Get-FileHash (Join-Path $restored $relative)).Hash) 'Cache restore changed generated bytes.'
  }
  Assert-CacheRejected { Restore-GenerationCache $restored $cache ($key + '-wrong') }
  $manifestPath = Join-Path $cache 'manifest.json'
  $manifest = Get-Content $manifestPath -Raw | ConvertFrom-Json
  $manifest.files[0].path = '../outside'
  $manifest | ConvertTo-Json -Depth 5 | Set-Content $manifestPath
  Assert-CacheRejected { Restore-GenerationCache $restored $cache $key }
  Save-GenerationCache $source $cache $key
  Add-Content (Join-Path $cache 'data/area_catalog.dat') 'corrupted'
  Assert-CacheRejected { Restore-GenerationCache $restored $cache $key }
  Assert-CacheCondition ((Get-FileHash "$source/data/area_catalog.dat").Hash -ceq (Get-FileHash "$restored/data/area_catalog.dat").Hash) 'Rejected cache partially overwrote valid generated data.'
  Save-GenerationCache $source $cache $key
  Remove-Item -LiteralPath (Join-Path $cache 'data/area_catalog.dat')
  Assert-CacheRejected { Restore-GenerationCache $restored $cache $key }
  Write-Output "Generation cache contracts passed: $assertions assertions."
} finally {
  $resolved = [IO.Path]::GetFullPath($root)
  $temporary = [IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\','/') + [IO.Path]::DirectorySeparatorChar
  if (-not $resolved.StartsWith($temporary, [StringComparison]::OrdinalIgnoreCase) -or [IO.Path]::GetFileName($resolved) -cnotmatch '^ironmon-generation-cache-[0-9a-f]{32}$') { throw 'Unsafe generation cache fixture cleanup.' }
  if (Test-Path -LiteralPath $resolved) { Remove-Item -LiteralPath $resolved -Recurse -Force }
}
