<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Ironmon.Tracker.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\data\type_coverage.json" Link="type_coverage.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\data\generation_custom_fusion_pool.bin" Link="generation_custom_fusion_pool.bin" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\data\generation_profile.json" Link="generation_profile.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\tests\fixtures\custom-fusion-pool-v1.json" Link="custom-fusion-pool-v1.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\..\tests\fixtures\generation-profile-v1.json" Link="generation-profile-v1.json" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="..\..\src\Ironmon.Tracker.Access\Ironmon.Tracker.Access.csproj" />
    <ProjectReference Include="..\..\src\Ironmon.Tracker.Connection\Ironmon.Tracker.Connection.csproj" />
    <ProjectReference Include="..\..\src\Ironmon.Tracker.Core\Ironmon.Tracker.Core.csproj" />
    <ProjectReference Include="..\..\src\Ironmon.Tracker.Protocol\Ironmon.Tracker.Protocol.csproj" />
    <ProjectReference Include="..\..\src\Ironmon.Tracker.Seeds\Ironmon.Tracker.Seeds.csproj" />
    <ProjectReference Include="..\..\tools\Ironmon.Tracker.AccessGenerator.Core\Ironmon.Tracker.AccessGenerator.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
